- name: Use jinja to replace vars in the config file
  hosts: all
  strategy: linear
  become: false

  tasks:

    - name: Check is config file exists
      stat:
        path: "{{ config }}"
      register: config_stat

    - name: Here is the var_values map
      debug:
        var: var_values
      when: config_stat.stat.exists and debug_operations is defined and debug_operations == "true"

    - name: Define a var named _ that contains the var values
      set_fact:
        _: "{{ var_values | from_yaml }}"
      when: config_stat.stat.exists

    - name: Create temporary file to store config file
      tempfile:
        state: file
        suffix: temp
      register: config_file
      when: config_stat.stat.exists

    - name: Render config in temp directory using Jinja
      template:
        src: "{{ config }}"
        dest: "{{ config_file.path }}"
        force: yes
      when: config_stat.stat.exists

    - name: Set the attribute CONFIG_FILE_PATH
      set_fact:
        CONFIG_FILE_PATH: "{{ config_file.path }}"
      when: config_stat.stat.exists

    - name: Here is the file
      debug:
        var: CONFIG_FILE_PATH
      when: config_stat.stat.exists and debug_operations is defined and debug_operations == "true"

    - name: Create temporary file to store kube config file
      tempfile:
        state: file
        suffix: kube_config_file
      register: kube_config_file

    - name: Render kube config in temp directory using Jinja
      template:
        src: "{{ kube_config }}"
        dest: "{{ kube_config_file.path }}"
        force: yes

    - name: Set the attribute KUBE_CONFIG_FILE_PATH
      set_fact:
        KUBE_CONFIG_FILE_PATH: "{{ kube_config_file.path }}"
